# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Fictions
tagline:             'Free Fictions Online'
description:         'Crafted with <3 by Elias.'
url:                 https://meniny.cn/fictions
# url:                 '/Users/Meniny/Documents/GitHub/Fictions/_site'
paginate:            10

# About/contact
author:
  name:              Elias Abel
  url:               https://twitter.com/_Meniny
  email:             admin@meniny.cn

# Custom vars
version:             2.0

# Social Media
github:				https://github.com/Meniny
twitter:			https://twitter.com/_Meniny
disqus:       eliass-cave

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Elias Abel
  codename:			Fictions
  link:         https://github.com/Meniny/fictions

collections:
  death_bus:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
      type: death_bus
    values:
      layout: "fiction"
      category: "Death Bus"
